image: gitlab/dind

services:
  - docker:dind

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
    - echo "This job will test code later"

compile-maven: 
  stage: build
  image: maven:latest
  script: 
    - echo "start maven install"
    - mvn clean install -D skipTests

test-docker:
  stage: build
  script:
    - docker info
    - docker login -u valentinabrivard -p b1817c9d-33ae-4963-8d72-dfd1091280f1
    - docker build -t valentinabrivard/javaimages:1.0.1 .
    - docker push valentinabrivard/javaimages:1.0.1

test-maven: 
  stage: test
  image: maven:latest
  script: 
    - echo "start maven test"
    - mvn test 

deploy-prod:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."

deploy-image-on-GCP: 
  stage: machine 
  image: ubuntu:latest
  before_script: 
    - apt install openssh
    - apt update -q
    - eval $(ssh-agent)
    - ssh-add < (echo "$SSHPRIVATE")
  script:
    - ssh cicd@104.199.78.46 && docker stop java && docker run valentinabrivard/javaimages
