steps:
- name: 'maven:latest'
  args: ['echo', 'debut build']
  args: ['mvn', 'clean', 'install', '-D', 'skipTests']
  timeout: 100s
- name: 'maven:latest'
  args: ['echo', 'debut du test maven']
  args: ['mvn', 'test']
  timeout: 100s 
- name: 'docker'
  args: ['echo', 'debut login dockerhub']
  args: ['docker', 'login', '-u', 'valentinabrivard', '-p', 'b1817c9d-33ae-4963-8d72-dfd1091280f1']
  args: ['docker', 'build', '-t', 'valentinabrivard/javaimages:1.0.1', '
  timeout: 10s
