steps:
- name: 'maven:latest'
  args: ['echo', 'debut build']
  args: ['mvn', 'clean', 'install', '-D', 'skipTests']
  timeout: 100s
- name: 'maven:latest'
  args: ['echo', 'debut du test maven']
  args: ['mvn', 'test']
  timeout: 100s  
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=valentinabrivard --password=b1817c9d-33ae-4963-8d72-dfd1091280f1']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t valentinabrivard/javaimages:1.0.1 .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push valentinabrivard/javaimages:1.0.1']

- name: node:latest
  entrypoint: bash
  args: ['cd' 'jsproject']
- name: node:latest
  entrypoint: npm
  args: ['install']
- name: node:latest
  entrypoint: npm
  args: ['run', 'build']
  timeout: 100s
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=valentinabrivard --password=b1817c9d-33ae-4963-8d72-dfd1091280f1']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['cd', 'jsproject']
  args: ['-c', 'docker build -t valentinabrivard/javascriptimages:1.0.1 .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['cd', 'jsproject']
  args: ['-c', 'docker push valentinabrivard/javascriptimages:1.0.1']

