steps:
- name: 'maven:latest'
  args: ['echo', 'debut build']
  args: ['mvn', 'clean', 'install', '-D', 'skipTests']
  timeout: 100s
- name: 'maven:latest'
  args: ['echo', 'debut du test maven']
  args: ['mvn', 'test']
  timeout: 100s 
- name: 'ubuntu'
  args: ['docker info']
  timeout: 10s
